# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7pfeqJK1YHx-yzcRMU6knGWXhgb7leN
"""

import streamlit as st
import google.generativeai as genai

genai.configure(api_key=st.secrets["GEMINI_API_KEY"])

st.title("🎓 CareerGuideBot")

context_previous = {
    "role": "user",
    "parts": (
        "You are CareerGuideBot, a friendly and motivating career guidance assistant. "
        "You help users choose career paths, educational goals, skill development plans, "
        "and provide motivational advice for interviews and personal growth. "
        "Keep responses short, clear, and encouraging (4–6 lines). "
        "Do NOT give financial, legal, or psychological advice. "
        "If the question is unrelated to career, education, or motivation, reply exactly with: "
        "'Sorry, I can only help with career, education, and motivation topics.'"
    )
}

model = genai.GenerativeModel("gemini-2.0-flash")

if "chat" not in st.session_state:
    st.session_state.chat = model.start_chat(history=[context_previous])

user_input = st.text_input("Ask your career question:")

if st.button("Send") and user_input:
    response = st.session_state.chat.send_message(user_input)
    st.write("💬 CareerGuideBot:")
    st.write(response.text)